appointments/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'appointments'

urlpatterns = [
    path('', views.home, name='home'),
    path('cars/', views.allCars, name='allCars'),
    path('car/<int:pk>/', views.seeMore, name='seeMore'),
]
# obsluga media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rental/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "rental"

urlpatterns = [
    path('create/<int:pk>', views.rezerwuj, name='rezerwuj'),
    path('myReservations/', views.mojeRezerwacje, name='mojeRezerwacje'),
    path('cancel/<int:pk>', views.anulujRezerwacje, name='anulujRezerwacje'), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservations/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appointments.urls')),
    path('users/', include('users.urls')),
    path('rental/', include('rental.urls')),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
    path('accound/', views.accound, name='accound'),
]

appointments/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from datetime import date

# Create your models here.

class Samochod(models.Model):
    id = models.AutoField(primary_key=True)
    marka = models.CharField(max_length=100)
    model = models.CharField(max_length=50)
    rok = models.IntegerField()
    cena_za_dzien = models.DecimalField(max_digits=8, decimal_places=2)
    opis = models.TextField()
    zdjecie = models.ImageField(upload_to='cars/', blank=True, null=True)

    def dostepny(self, data_od, data_do):
        return not self.rezerwacje.filter(
            status='confirmed',
            data_od__lt=data_do,
            data_do__gt=data_od
        ).exists()

    def __str__(self):
        return f"{self.marka} - {self.model} - {self.rok}"
    
class Rezerwacja(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Oczekuje'),
        ('confirmed', 'Potwierdzona'),
        ('cancelled', 'Anulowana'),
    ]
    id = models.AutoField(primary_key=True)
    klient = models.ForeignKey(User, on_delete=models.CASCADE)
    auto = models.ForeignKey(Samochod, on_delete=models.CASCADE, related_name='rezerwacje')
    data_od = models.DateField()
    data_do = models.DateField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    cena_ogolna = models.DecimalField(max_digits=10, decimal_places=2, null=True , blank=True)
    data_utworzenia = models.DateTimeField(auto_now_add=True)

    def clean(self):
        if self.data_od >= self.data_do:
            raise ValidationError("Data zakonczenia musi byc pozniej niz data rozpoczecia")

        if self.data_od < date.today():
            raise ValidationError("Nie rezerwuj w przeszlosci")
        
        if not self.auto.dostepny(self.data_od, self.data_do):
            raise ValidationError("Auto niedostepne w wybranym terminie")

    def save(self, *args, **kwargs):
        self.full_clean()
        dni = (self.data_do - self.data_od).days
        self.cena_ogolna = dni * self.auto.cena_za_dzien
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.auto} - {self.data_od} - {self.data_do}"

appointments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Samochod

def home(request):
    auta = Samochod.objects.all()[:3]
    return render(request, 'appointments/homePage.html', {'auta': auta})

def allCars(request):
    auta = Samochod.objects.all()
    return render(request, 'appointments/allCars.html', {'auta': auta})

def seeMore(request, pk):
    auta = get_object_or_404(Samochod, pk=pk)
    return render(request, "appointments/seeMore.html", {'auta': auta})

appointments/templates/appointments/allCars.html
{% extends "layout.html" %}

{% block title %}
    Wyporzyczalnia
{% endblock %}

{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'appointments/style.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        {% for auto in auta %}
            <div class="panel">
                <h3>{{auto.marka}}</h3>
                <p>Model: {{auto.model}}</p>
                <p>Rok: {{auto.rok}}</p>
                <p>Cena za dzień: {{auto.cena_za_dzien}} zl</p>
                <img src="{{ auto.zdjecie.url }}" alt="obraek samochodu">
                <a href="{% url 'appointments:seeMore' pk=auto.pk %}"><button>Zobacz wiecej</button></a>
                <a href="{% url 'rental:rezerwuj' pk=auto.pk %}"><button class="rezerwuj">Zarezerwuj</button></a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

appointments/templates/appointments/homePage.html
{% extends "layout.html" %}

{% block title %}
    Wyporzyczalnia
{% endblock %}

{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'appointments/style.css' %}">
{% endblock %}

{% block content %}
    <header>
        <h1>Witaj w wyporzyczalni samochodów</h1>
        <p>Wybierz dostępny samochód, wolny termin i jeździj!</p>
    </header>
    <div class="container">
        {% for auto in auta %}
            <div class="panel">
                <h3>{{auto.marka}}</h3>
                <p>Model: {{auto.model}}</p>
                <p>Rok: {{auto.rok}}</p>
                <p>Cena za dzień: {{auto.cena_za_dzien}} zl</p>
                <img src="{{ auto.zdjecie.url }}" alt="obraz">
                <a href="{% url 'appointments:seeMore' pk=auto.pk %}"><button>Zobacz wiecej</button></a>
                <a href="{% url 'rental:rezerwuj' pk=auto.pk %}"><button class="rezerwuj">Zarezerwuj</button></a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

appointments/templates/appointments/seeMore.html
{% extends "layout.html" %}

{% block title %}
    Wyporzyczalnia
{% endblock %}

{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'appointments/style.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel">
            <h3>{{auta.marka}}</h3>
            <p>Model: {{auta.model}}</p>
            <p>Rok: {{auta.rok}}</p>
            <p>Cena za dzień: {{auta.cena_za_dzien}} zl</p>
            <p class="opis">{{auta.opis}}</p>
            <img src="{{ auta.zdjecie.url }}" alt="obraz">
            <a href="{% url 'rental:rezerwuj' pk=auta.pk %}"><button class="rezerwuj">Zarezerwuj</button></a>
        </div>
    </div>
{% endblock %}