rental/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "rental"

urlpatterns = [
    path('create/<int:pk>', views.rezerwuj, name='rezerwuj'),
    path('myReservations/', views.mojeRezerwacje, name='mojeRezerwacje'),
    path('cancel/<int:pk>', views.anulujRezerwacje, name='anulujRezerwacje'), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservations/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appointments.urls')),
    path('users/', include('users.urls')),
    path('rental/', include('rental.urls')),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),
    path('accound/', views.accound, name='accound'),
]

rental/models.py
from django.db import models

# Create your models here.

rental/forms.py
from django import forms
from appointments.models import Rezerwacja

class RezerwacjaForm(forms.ModelForm):
    class Meta:
        model = Rezerwacja
        fields = ['data_od', 'data_do']
        widgets = {
            'data_od': forms.DateInput(attrs={'type': 'date'}),
            'data_do': forms.DateInput(attrs={'type': 'date'}),
        }

rental/views.py
from django.shortcuts import render, get_object_or_404, redirect
from appointments.models import Samochod, Rezerwacja
from django.contrib.auth.decorators import login_required
from .forms import RezerwacjaForm
from django.contrib import messages
from datetime import date, timedelta
# Create your views here.

@login_required
def rezerwuj(request, pk):
    auto = get_object_or_404(Samochod, pk=pk)

    wolne = wolneTerminy(auto)

    if request.method == 'POST':
        form = RezerwacjaForm(request.POST)
        form.instance.auto = auto # inaczej wywala blad
        if form.is_valid():
            rezerwacja = form.save(commit=False)
            rezerwacja.klient = request.user
            rezerwacja.auto = auto
            rezerwacja.save()

            if request.headers.get('x-requested-with') == 'XMLHyypRequest':
                return JsonResponse({'succes': True})

            return redirect('/rental/myReservations/')
    else:
        form = RezerwacjaForm()

    return render(request, 'rental/create.html', {'form': form, 'auto': auto, 'wolne': wolne})

@login_required
def mojeRezerwacje(request):
    rezerwacje = Rezerwacja.objects.filter(klient=request.user)
    return render(request, "rental/myReservations.html", {'rezerwacje': rezerwacje})

@login_required
def anulujRezerwacje(request, pk):
    if request.method == "POST":
        rezerwacje = get_object_or_404(Rezerwacja, pk=pk, klient=request.user)
        if rezerwacje.status == "confirmed":
            messages.error(request, "Rezerwacja jest już zatwierdzona, nie możesz jej anulować!")
        else:
            rezerwacje.status = 'cancelled'
            rezerwacje.save()

    return redirect('rental:mojeRezerwacje')

def wolneTerminy(auto):
    dzis = date.today()
    koniec = dzis + timedelta(days=30)
    rezerwacje = auto.rezerwacje.filter(status__in=['pending', 'confirmed'], data_do__gte=dzis, data_od__lte=koniec).order_by('data_od')

    wolne = []
    aktualna = dzis

    for rezerwacja in rezerwacje:
        if rezerwacja.data_od > aktualna:
            wolne.append((aktualna, rezerwacja.data_od - timedelta(days=1)))
        if rezerwacja.data_do >= aktualna:
            aktualna = rezerwacja.data_do + timedelta(days=1)
        
    if aktualna <= koniec:
        wolne.append((aktualna, koniec))

    return wolne

reservations/rental/views.py
from django.shortcuts import render, get_object_or_404, redirect
from appointments.models import Samochod, Rezerwacja
from django.contrib.auth.decorators import login_required
from .forms import RezerwacjaForm
from django.contrib import messages
# Create your views here.

@login_required
def rezerwuj(request, pk):
    auto = get_object_or_404(Samochod, pk=pk)

    if request.method == 'POST':
        form = RezerwacjaForm(request.POST)
        form.instance.auto = auto # inaczej wywala blad
        if form.is_valid():
            rezerwacja = form.save(commit=False)
            rezerwacja.klient = request.user
            rezerwacja.auto = auto
            rezerwacja.save()
            return redirect('/rental/myReservations/')
    else:
        form = RezerwacjaForm()

    return render(request, 'rental/create.html', {'form': form, 'auto': auto})

@login_required
def mojeRezerwacje(request):
    rezerwacje = Rezerwacja.objects.filter(klient=request.user)
    return render(request, "rental/myReservations.html", {'rezerwacje': rezerwacje})

@login_required
def anulujRezerwacje(request, pk):
    if request.method == "POST":
        rezerwacje = get_object_or_404(Rezerwacja, pk=pk, klient=request.user)
        if rezerwacje.status == "confirmed":
            messages.error(request, "Rezerwacja jest już zatwierdzona, nie możesz jej anulować!")
        else:
            rezerwacje.status = 'cancelled'
            rezerwacje.save()

    return redirect('rental:mojeRezerwacje')

rental/templates/rental/create.html
{% extends "layout.html" %}

{% block title %}
    Zarezerwuj
{% endblock %}

{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'rental/style.css' %}">
{% endblock %}

{% block content %}
    <div class="terminyRezerwacji">
        <div class="wolne">
            <h2>Wolne terminy w najbliższych 30 dniach</h2>
            <ul id="clickValues">
                {% for od, do in wolne %}
                    <li>{{ od|date:"d.m.Y" }} - {{ do|date:"d.m.Y" }}</li>
                {% empty %}
                    <li>Brak wolnych terminow</li>
                {% endfor %}
            </ul>
        </div>
        <div class="panelUtworzenia">
            <h2>Wybierz daty</h2>
            <form id="createForm" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Zarezerwuj</button>
            </form>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        const form = document.getElementById('createForm');

        form.addEventListener('submit', (e) => {
            e.preventDefault();

            const dataForm = new FormData(form);

            fetch('', {
                method: 'POST',
                body: dataForm,
                headers: {
                    'X_CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value
                }
            })
            .then(response => response.json())
            .then(data => {
                if(data.success){
                    alert("Zapisano")
                } else{
                    alert(data.error);
                }
            })
            .catch(err => console.error(err));
        });
    </script>
{% endblock %}

rental/templates/rental/myReservations.html
{% extends "layout.html" %}

{% block title %}
    Twoje rezerwacje
{% endblock %}

{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'rental/style.css' %}">
{% endblock %}

{% block content %}
    <h1>Moje rezerwacje</h1>
    <div class="container">
        {% for rezerwacja in rezerwacje %}
            <div class="panelRezerwacji">
                <p>{{ rezerwacja.auto }}r.</p>
                <p>od: {{ rezerwacja.data_od }}</p>
                <p>do: {{ rezerwacja.data_do }}</p>
                <p>ogolna cena: {{ rezerwacja.cena_ogolna }}zl</p>
                <p>data utworzenia: {{ rezerwacja.data_utworzenia }}</p>
                <img src="{{ rezerwacja.auto.zdjecie.url }}" alt="zdjecie samochodu">

                <p class="statusRez">Status rezerwacji: 
                    <span title="Jeśli rezerwacja będzie zaakceptowana, to już nie możesz jej anulować!">{{ rezerwacja.status }}</span>
                </p>

                {% if rezerwacja.status != 'cancelled'  %}
                    <form action="{% url 'rental:anulujRezerwacje' rezerwacja.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Anuluj rezerwacje</button>
                        {% for message in messages %}
                            <ul>
                                <li class="komunikat">{{ message }}</li>
                            </ul>
                        {% endfor %}
                    </form>
                {% else %}
                    <div class="anulowane">
                        <p>Rezerwacja anulowana</p>
                        <a href="/cars/">Zarezerwuj cos nowego</a>
                    </div>
                {% endif %}
            </div>
        
        {% empty %}
            <div class="empty">
                <p>Nie masz jeszcze rezerwacji</p>
                <a href="/cars/">Wybierz jakieś auto</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}